fix(hack): override ec bundle
redhat-appstudio/release-service-catalog pull request #261
Opened 2023-10-25 18:06 UTC by scoheb

2023-10-25 18:07 UTC, johnbieren submitted a review, later dismissed

2023-10-25 18:08 UTC, happybhati submitted a review, later dismissed

2023-10-26 07:49 UTC, mmalina requested changes
There is at least one unrelated commit included here (the repository+commonTag fix). I guess you can rebase once that fix is merged.

But we definitely need some description here to explain why this is needed.

2023-10-26 11:44 UTC, scoheb commented
Hopefully this PR will not be needed once EC merges their fix in infra...

The extra commits are just a result of me trying to test last night. I needed both fixes.

2023-10-31 19:33 UTC, closed without merging