fix: supply both image index and image manifest digests when creating…
redhat-appstudio/release-service-catalog pull request #388
Opened 2024-03-25 19:07 UTC by ralphbean

… pyxis image record

See also https://github.com/redhat-appstudio/release-service-utils/pull/134

2024-03-25 19:09 UTC, scoheb commented on tasks/create-pyxis-image/create-pyxis-image.yaml
> +                ARCH=$(jq '.platform.os' <<< "$ARCH_DETAIL")
```suggestion
                ARCH=$(jq '.platform.architecture' <<< "$ARCH_DETAIL")
```

2024-03-26 12:42 UTC, johnbieren requested changes
This can't be merged without the task images updated (which I know you can't do until the utils PR is merged, but marking this here so it is not accidentally merged)

2024-03-26 12:46 UTC, johnbieren commented on tasks/create-pyxis-image/README.md
> +## Changes in 2.2.1
Should be 2.2.2

2024-03-28 19:39 UTC, ralphbean commented on tasks/create-pyxis-image/README.md
> +## Changes in 2.2.1
Updated!

2024-03-29 02:46 UTC, jinqi7 commented
/retest

2024-04-09 20:49 UTC, ralphbean commented
/retest-required

2024-04-10 18:03 UTC, ralphbean commented
/retest-required

2024-04-11 17:14 UTC, johnbieren reviewed
Code changes LGTM, but not approving yet as we need https://github.com/konflux-ci/release-service-utils/pull/134 to merge and then the image used for these three tasks to be updated to the resulting image

2024-04-12 15:35 UTC, johnbieren commented
> This can't be merged without the task images updated (which I know you can't do until the utils PR is merged, but marking this here so it is not accidentally merged)

The image tag to use for these tasks is `b3059c67d4bdb6c9cf1739fdfb2c0cb595fe0f86`

2024-04-12 18:14 UTC, ralphbean commented
> The image tag to use for these tasks is b3059c67d4bdb6c9cf1739fdfb2c0cb595fe0f86

Updated.

2024-04-12 18:24 UTC, johnbieren approved these changes

2024-04-15 13:16 UTC, ralphbean commented
/retest-required

2024-04-15 22:51 UTC, merged