fix(RHTAPREL-842): FBC should error when preGA & hotfix both set
redhat-appstudio/release-service-catalog pull request #392
Opened 2024-04-09 10:38 UTC by theflockers

This commit adds a check to make sure fbc.preGA and fbc.hotfix can not be both set at once

Signed-off-by: Leandro Mendes <lmendes@redhat.com>

2024-04-09 12:06 UTC, davidmogar requested changes

2024-04-09 12:06 UTC, davidmogar commented on tasks/add-fbc-contribution/add-fbc-contribution.yaml
> +          echo "fbc.preGA and fbc.hotfix are mutually exclusive. Please set just one in the releasePlanAdmission"
```suggestion
          echo "fbc.preGA and fbc.hotfix are mutually exclusive. Please set just one in the ReleasePlanAdmission"
```

2024-04-09 12:43 UTC, theflockers commented on tasks/add-fbc-contribution/add-fbc-contribution.yaml
> +          echo "fbc.preGA and fbc.hotfix are mutually exclusive. Please set just one in the releasePlanAdmission"
fixed!

2024-04-09 13:38 UTC, theflockers commented
/retest

2024-04-10 08:15 UTC, theflockers commented
/retest

2024-04-10 08:18 UTC, davidmogar approved these changes

2024-04-11 09:02 UTC, theflockers commented
/retest

2024-04-11 13:19 UTC, theflockers commented
/retest

2024-04-11 16:18 UTC, johnbieren approved these changes

2024-04-15 08:07 UTC, theflockers commented
/retest

2024-04-16 13:53 UTC, theflockers commented
/retest

2024-04-16 14:53 UTC, theflockers commented
/retest

2024-04-17 07:58 UTC, theflockers commented
/retest

2024-04-17 09:36 UTC, theflockers commented
/retest

2024-04-18 09:13 UTC, theflockers commented
/retest

2024-04-19 13:44 UTC, theflockers commented
/retest

2024-04-23 07:20 UTC, jinqi7 commented
@theflockers , the e2e-tests of you PR will fail until the [PR](https://github.com/redhat-appstudio/e2e-tests/pull/1132) is merged.

2024-04-23 12:41 UTC, johnbieren commented
/test release-pipelines-e2e-suite

2024-04-23 14:26 UTC, johnbieren commented
/test release-pipelines-e2e-suite

2024-04-23 23:54 UTC, jinqi7 commented
/retest

2024-04-24 07:25 UTC, theflockers commented
/retest

2024-04-24 07:53 UTC, theflockers commented
/test release-pipelines-e2e-suite

2024-04-24 07:55 UTC, theflockers commented
/retest

2024-04-24 08:08 UTC, theflockers commented
/retest

2024-04-24 12:15 UTC, jinqi7 commented
/retest

2024-04-24 13:45 UTC, johnbieren commented
/test release-pipelines-e2e-suite

2024-04-24 15:23 UTC, johnbieren commented
/test release-pipelines-e2e-suite

2024-04-24 19:24 UTC, theflockers commented
/retest

2024-04-25 01:24 UTC, jinqi7 commented
/test release-pipelines-e2e-suite

2024-04-25 08:19 UTC, theflockers commented
/test release-pipelines-e2e-suite

2024-04-25 10:31 UTC, psturc commented
/test release-pipelines-e2e-suite

2024-04-25 11:53 UTC, jinqi7 commented
/test release-pipelines-e2e-suite

2024-04-25 13:54 UTC, merged