fix(KFLUXBUGS-1264): increase request timeout
redhat-appstudio/release-service-catalog pull request #420
Opened 2024-05-15 21:25 UTC by scoheb

- The RADAS timeout when it fails to receive a response is 5 mins. We double the requestTimeout to allow RADAS to retry its request.

2024-05-15 21:32 UTC, happybhati requested changes
The pipeline version needs to be updated, and update README

```
    app.kubernetes.io/version: "2.5.1"
```

2024-05-15 21:40 UTC, happybhati approved these changes

2024-05-15 21:49 UTC, scoheb commented
this causes the tests to take too long. Will not change the default

2024-05-15 21:49 UTC, closed without merging

2024-05-16 06:53 UTC, mmalina commented
> this causes the tests to take too long. Will not change the default

That's too bad. The tests definitely shouldn't have to wait for this. They can easily specify their own timeout (other than the default) when calling the task.