feat(RELEASE-1006): update references to `release-service-utils`
redhat-appstudio/release-service-catalog pull request #473
Opened 2024-07-10 10:34 UTC by seanconroy2021

This commit addresses [CVE-2024-3727]( https://github.com/advisories/GHSA-6wvf-f2vw-3425) by bumping images.

Change include:
- Bumping quay.io/konflux-ci/release-service-utils
  to the latest available tag.

Signed-off-by: Sean Conroy <sconroy@redhat.com>

2024-07-10 10:34 UTC, seanconroy2021 commented
/test all

2024-07-10 19:17 UTC, johnbieren requested changes

2024-07-10 19:17 UTC, johnbieren commented on pipelines/rhtap-service-push/README.md
> +## chnages in 3.11.0
changes not chnages

2024-07-10 19:17 UTC, johnbieren commented on tasks/add-fbc-contribution/README.md
> +## chnages in 3.1.0
changes not chnages

2024-07-10 19:17 UTC, johnbieren commented on tasks/base64-encode-checksum/README.md
> +## Changes in 1.2.0
missing new line before this one

2024-07-10 19:17 UTC, johnbieren commented on tasks/check-data-keys/README.md
> +## Changes in 0.8.0
missing new line before this one

2024-07-10 19:17 UTC, johnbieren commented on tasks/cleanup-workspace/README.md
> +## Changes in 0.8.0
new line before

2024-07-10 19:17 UTC, johnbieren commented on tasks/update-infra-deployments/README.md
> +## Changes in 1.2.0
missing new line before

2024-07-10 20:37 UTC, seanconroy2021 commented
@johnbieren Fixed

2024-07-11 01:02 UTC, johnbieren approved these changes

2024-07-11 05:53 UTC, seanconroy2021 commented
/retest

2024-07-11 11:52 UTC, seanconroy2021 commented
/retest

2024-07-11 12:56 UTC, seanconroy2021 commented
/retest

2024-07-11 17:13 UTC, merged