feat: nicer display for fbc pipelines
redhat-appstudio/release-service-catalog pull request #551
Opened 2024-09-11 20:05 UTC by ralphbean

Functionally, this was all doing the right thing before. Tasks later in the pipeline wait automatically for preceding tasks if the output of a preceding task is used as a param of a later task.

However, our UI doesn't render the pipeline nicely if we only rely on those dependencies. By using `runAfter`, we can hint to the UI how the pipelinerun should be rendered.

2024-09-11 20:24 UTC, happybhati requested changes
Small addition
Bump up pipeline [version](https://github.com/konflux-ci/release-service-catalog/pull/551/files#diff-3778095b07e9be9d621f33c7b73cd675da51308dd923e44c58458738d8c023cdL7) and add README-changelog entry for the updated version.

And thanks for the PR 🫡

2024-09-11 21:32 UTC, ralphbean commented
@happybhati done, updated!

2024-09-11 23:11 UTC, happybhati commented
> @happybhati done, updated!

I think you updated **task** version and readme instead of **pipeline**.

2024-09-12 08:25 UTC, mmalina commented on tasks/update-ocp-tag/README.md
Agreed with Happy, this is the wrong README and wrong place to bump the version - those changes should be in the pipeline.

BTW, we had this exact issue before and added some explicit `runAfter` values in other pipelines. But not this one I guess :)

2024-09-12 12:37 UTC, johnbieren commented on tasks/update-ocp-tag/README.md
@davidmogar did you ever open a bug against openshift pipelines for this?

2024-09-13 11:58 UTC, ralphbean commented
> > @happybhati done, updated!
> 
> I think you updated **task** version and readme instead of **pipeline**.

:cry: oh my. Fixing!

2024-09-13 12:09 UTC, ralphbean commented
OK, let's try that again.

2024-09-13 14:32 UTC, davidmogar commented on tasks/update-ocp-tag/README.md
Never offered to do it ;)

2024-09-13 14:32 UTC, davidmogar approved these changes

2024-09-13 14:40 UTC, johnbieren commented on tasks/update-ocp-tag/README.md
I will create you a critical Jira to open it :wink:

2024-09-13 14:40 UTC, happybhati approved these changes

2024-09-13 14:41 UTC, merged