fix: avoid duplicates in component tags
redhat-appstudio/release-service-catalog pull request #606
Opened 2024-10-09 11:41 UTC by mmalina

- Tweaked processing of tags to automatically remove any duplicate tags in a component

This came up in a discussion with the osci team.
The idea is that they might want to have e.g.:

```
tags:
  - 9.5
  - {{ labels.release }}
```

In most cases, these will be different, but they might be the same. The pipeline would probably still work, but we should really remove any duplicates.

2024-10-09 11:51 UTC, jpopelka approved these changes

2024-10-09 12:33 UTC, happybhati approved these changes

2024-10-09 12:34 UTC, happybhati requested changes
Maybe task test needs an update?  did not notice at first, its failing.

2024-10-10 15:04 UTC, mmalina commented on tasks/apply-mapping/apply-mapping.yaml
> +                translated_tags="$(jq -c --arg tag "$tag" '. + [$tag] | unique' <<< "$translated_tags")"
As Happy pointed out, the tests failed. It turns out that [`uniq` also sorts the items](https://jqlang.github.io/jq/manual/#unique-unique_by) as a side effect. 

```
[check-result : check-result] + test '["123456","defaultTag","foo-123456","tag-labelvalue","tag1-2024-07-29","tag2-2024-07-29","tag3-2024-07-29-testrev","testrev","testrev-bar","testrevision","testrevision-abc"]' == '["defaultTag","foo-123456","tag-labelvalue","tag1-2024-07-29","tag2-2024-07-29","tag3-2024-07-29-testrev","123456","testrevision-abc","testrev-bar","testrevision","testrev"]'

  Pipelinerun test-apply-mapping-tag-expansion failed
```

So the question is: Do we care? Is this ok? Probably yes? @johnbieren WDYT?

2024-10-10 18:30 UTC, mmalina commented on tasks/apply-mapping/apply-mapping.yaml
> +                translated_tags="$(jq -c --arg tag "$tag" '. + [$tag] | unique' <<< "$translated_tags")"
nvm, I solved it another way and now the order stays.

2024-10-10 18:46 UTC, mmalina commented
> Maybe task test needs an update? did not notice at first, its failing.

I reworked it a bit. Please check now.

2024-10-11 06:33 UTC, mmalina commented
/retest

2024-10-11 11:57 UTC, happybhati approved these changes

2024-10-11 11:58 UTC, merged