chore: bump release-service-utils in push-snapshot
redhat-appstudio/release-service-catalog pull request #671
Opened 2024-11-05 17:59 UTC by lcarva

The new image brings a new version of the get-image-architecture script which can properly handle a Tekton bundle. This update was previously done to the apply-mapping Task, but the push-snapshot Task also relies on it.

Ref: KFLUXBUGS-1741

2024-11-05 18:19 UTC, happybhati requested changes
Hey @lcarva , May I ask for a task version bump and update in README? You can take an example from this recent [PR](https://github.com/konflux-ci/release-service-catalog/commit/1cfbce57a3683d6aaf89833b9379036d813c7d51)

2024-11-05 18:26 UTC, lcarva commented
> Hey @lcarva , May I ask for a task version bump and update in README? You can take an example from this recent [PR](https://github.com/konflux-ci/release-service-catalog/commit/1cfbce57a3683d6aaf89833b9379036d813c7d51)

Done! Thanks for the prompt review.

2024-11-05 18:39 UTC, johnbieren approved these changes

2024-11-05 18:39 UTC, johnbieren commented
/retest

2024-11-05 18:40 UTC, happybhati approved these changes

2024-11-05 19:02 UTC, johnbieren commented
/retest

2024-11-05 20:13 UTC, lcarva commented
I see some of this in the e2e test failures:

```
"conditions": [                                                                     
135                     {                                                                               
136                         "lastTransitionTime": "2024-11-05T19:51:42Z",                               
137                         "message": "Error retrieving pipeline for pipelinerun ex-registry-managed-duah/managed-ql84k: reso    lver failed to get Pipeline : error requesting remote resource: error getting \"Git\" \"ex-registry-managed-duah/git-a11a6    8459a38cb2e02133eae67712474\": clone error: authentication required",
138                         "reason": "CouldntGetPipeline",                                             
139                         "status": "False",                                                          
140                         "type": "Succeeded"                                                         
141                     }                                                                               
142                 ],   
```

Is authentication really needed? If so, maybe the problem is because this PR comes from a fork making the GitHub secrets not available.

2024-11-06 09:01 UTC, mmalina commented
> I see some of this in the e2e test failures:
> 
> ```
> "conditions": [                                                                     
> 135                     {                                                                               
> 136                         "lastTransitionTime": "2024-11-05T19:51:42Z",                               
> 137                         "message": "Error retrieving pipeline for pipelinerun ex-registry-managed-duah/managed-ql84k: reso    lver failed to get Pipeline : error requesting remote resource: error getting \"Git\" \"ex-registry-managed-duah/git-a11a6    8459a38cb2e02133eae67712474\": clone error: authentication required",
> 138                         "reason": "CouldntGetPipeline",                                             
> 139                         "status": "False",                                                          
> 140                         "type": "Succeeded"                                                         
> 141                     }                                                                               
> 142                 ],   
> ```
> 
> Is authentication really needed? If so, maybe the problem is because this PR comes from a fork making the GitHub secrets not available.

No, authentication should definitely not be required. @jinqi7 any idea what's wrong?

2024-11-06 13:45 UTC, johnbieren commented
Considering e2e passed elsewhere, I am under the impression this was a flake because I don't see any way this PR could have caused that failure (it would still be nice to hear Jing's response). @lcarva can you rebase this?

2024-11-06 16:38 UTC, johnbieren commented
/retest

2024-11-06 18:33 UTC, johnbieren commented
/retest

2024-11-06 21:08 UTC, johnbieren commented
/retest

2024-11-06 23:14 UTC, johnbieren commented
/retest

2024-11-07 01:13 UTC, johnbieren commented
/retest

2024-11-07 06:12 UTC, happybhati commented
/retest

2024-11-18 20:17 UTC, johnbieren commented
```
  - lastTransitionTime: "2024-11-18T19:59:59Z"
    message: 'Error retrieving pipeline for pipelinerun managed-release-team-tenant/managed-85pwl:
      resolver failed to get Pipeline : error requesting remote resource: error getting
      "Git" "managed-release-team-tenant/git-e5f50bffcc9847648818543d66a9d75d": clone
      error: authentication required'
```
Not sure what that is about, let's see if it reproduces

2024-11-18 20:17 UTC, johnbieren commented
/retest

2024-11-19 04:21 UTC, jinqi7 commented
> ```
>   - lastTransitionTime: "2024-11-18T19:59:59Z"
>     message: 'Error retrieving pipeline for pipelinerun managed-release-team-tenant/managed-85pwl:
>       resolver failed to get Pipeline : error requesting remote resource: error getting
>       "Git" "managed-release-team-tenant/git-e5f50bffcc9847648818543d66a9d75d": clone
>       error: authentication required'
> ```
> 
> Not sure what that is about, let's see if it reproduces

It's caused by rctx.repoName [here](https://github.com/konflux-ci/e2e-tests/blob/fa2e7ac423f59a0e73565fa6033d9b7bf58edffc/magefiles/rulesengine/repos/release_service_catalog.go#L60C131-L60C144)  since the remote repoName for the PR is `release-service-bundles`.  Currently, we only support the same repoName for the forked repo.

2024-11-19 09:50 UTC, mmalina commented
Thanks, @jinqi7 . So until that is fixed, to make this work, can you rename your fork to release-service-catalog @lcarva ? It might break this PR, depending on how Github refers to the PR source and target repos internally, but hopefully not.

2024-11-19 14:37 UTC, johnbieren commented
> > ```
> >   - lastTransitionTime: "2024-11-18T19:59:59Z"
> >     message: 'Error retrieving pipeline for pipelinerun managed-release-team-tenant/managed-85pwl:
> >       resolver failed to get Pipeline : error requesting remote resource: error getting
> >       "Git" "managed-release-team-tenant/git-e5f50bffcc9847648818543d66a9d75d": clone
> >       error: authentication required'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not sure what that is about, let's see if it reproduces
> 
> It's caused by rctx.repoName [here](https://github.com/konflux-ci/e2e-tests/blob/fa2e7ac423f59a0e73565fa6033d9b7bf58edffc/magefiles/rulesengine/repos/release_service_catalog.go#L60C131-L60C144) since the remote repoName for the PR is `release-service-bundles`. Currently, we only support the same repoName for the forked repo. Filed a [bug](https://issues.redhat.com/browse/KFLUXBUGS-1882).

Ah! How interesting. Great find @jinqi7

2024-11-21 15:28 UTC, johnbieren commented
Closing in favor of https://github.com/konflux-ci/release-service-catalog/pull/706 because of the fork name

2024-11-21 15:28 UTC, closed without merging